// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaLaKvmVCai0E2BCpgEWo8E8z07w6am48',
    appId: '1:677160284254:web:e13c37bd542138d9f904cf',
    messagingSenderId: '677160284254',
    projectId: 'koodiaranachauffeur',
    authDomain: 'koodiaranachauffeur.firebaseapp.com',
    storageBucket: 'koodiaranachauffeur.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-w1iryBI1YqV2OWUmcOSntyz1QzCM5ek',
    appId: '1:677160284254:android:c735620bd2d50694f904cf',
    messagingSenderId: '677160284254',
    projectId: 'koodiaranachauffeur',
    storageBucket: 'koodiaranachauffeur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqW1b-WhwWNQE7-sNqg9CB8F6AQ8al7ao',
    appId: '1:677160284254:ios:e4acc27691af4632f904cf',
    messagingSenderId: '677160284254',
    projectId: 'koodiaranachauffeur',
    storageBucket: 'koodiaranachauffeur.firebasestorage.app',
    iosBundleId: 'com.example.koodiaranaChauffeur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqW1b-WhwWNQE7-sNqg9CB8F6AQ8al7ao',
    appId: '1:677160284254:ios:e4acc27691af4632f904cf',
    messagingSenderId: '677160284254',
    projectId: 'koodiaranachauffeur',
    storageBucket: 'koodiaranachauffeur.firebasestorage.app',
    iosBundleId: 'com.example.koodiaranaChauffeur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaLaKvmVCai0E2BCpgEWo8E8z07w6am48',
    appId: '1:677160284254:web:391a5f715983327ff904cf',
    messagingSenderId: '677160284254',
    projectId: 'koodiaranachauffeur',
    authDomain: 'koodiaranachauffeur.firebaseapp.com',
    storageBucket: 'koodiaranachauffeur.firebasestorage.app',
  );
}
